INSERT INTO public.preguntas VALUES (1, 1, '¿Qué nombre recibe la ciencia que estudia acerca de Dios?', 2, 1, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (2, 2, '¿Qué significa el término trinidad?', 3, 2, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (3, 3, '¿Que nombre recibe la doctrina que estudia acerca de Jesucristo?', 2, 1, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (4, 4, 'Compruebe con un texto donde hable de la trinidad de Dios', 3, 3, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (5, 5, '¿Cual es la voluntad del Padre para nosotros, según  1 Ts 4:3?', 2, 3, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (6, 6, '¿La naturaleza de Dios nos indica que Él es?', 3, 2, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (7, 7, 'Indique tres(3) atributos divinos de Dios Padre ', 3, 1, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (8, 8, '¿Cuando decimos que el nacimiento de Cristo fue profetizado y anunciado, nos referimos a quien?', 2, 1, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (9, 9, 'Menciona tres nombres de Dios Padre.', 3, 3, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (10, 10, '¿Como Cristo dividió la historia?', 3, 1, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (11, 11, '¿Quien en la trinidad es conocido como el "Parakleto" ?', 2, 3, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (12, 12, '¿La palabra trinidad aparece en la Biblia?', 1, 2, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (13, 13, '¿La segunda persona de la trinidad es Cristo?', 1, 1, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (14, 14, '¿Para quien fue declarada la profecía de Isaías 61:1', 2, 2, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (15, 15, '¿Cuales eran las condiciones que debía tener Cristo para poder ser llamado el Cordero de Dios.', 3, 4, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (16, 16, '¿Cuál es la evidencia visible del bautismo en el Espíritu Santo?', 2, 1, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (17, 17, '¿Cuales fueron las dos naturalezas que poseía Jesucristo?', 3, 1, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (18, 18, '¿Que significa el unigénito entres los hombres?', 3, 3, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (19, 19, '¿Como fue el embarazo de María, según la ciencia? ', 3, 3, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (20, 20, '¿Con que esta asociada la encarnación de Cristo?', 2, 3, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (21, 21, '¿Por que es importante la genealogía de Cristo? ', 3, 4, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (22, 22, 'Nombra cuatro obras de Cristo en la tierra ', 3, 2, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (23, 23, '¿Como se llamó el lugar de la transfiguración''? ', 3, 2, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (24, 24, '¿Hubo derramamiento del Espíritu Santo en el Antiguo Testamento?', 1, 1, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (25, 25, '¿Quienes aparecieron rodeados de gloria en el monte de la transfiguración?', 3, 1, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (26, 26, '¿Quienes de los discípulos estuvieron en el monte de la transfiguración ', 3, 2, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (27, 27, 'Mencione cuantos bautismos hay en la Biblia', 3, 3, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (28, 28, '¿El Espíritu Santo habla?, de ser cierto, cite un texto bíblico', 3, 3, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (29, 29, 'Diga cuantos son los símbolos del Espíritu Santo y explique alguno de ellos con cita bíblica ', 3, 4, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (30, 30, 'En Antiguo Testamento. El Espíritu Santo de Dios moraba en los creyentes?', 1, 1, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (31, 31, '¿Cual fue la promesa cumplida del profeta Joel en Hechos 2:4', 3, 1, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (32, 32, 'Mencione tres (3) nombres compuesto de Jehová ', 3, 3, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (33, 33, '¿Que quiere decir la omnipresencia de Dios?', 3, 1, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (34, 34, '¿Como llamaron los profetas al Señor Jesús?', 3, 2, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (35, 35, '¿Como llamaron los apóstoles a Jesús?', 3, 3, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (36, 36, 'Nombre las prerrogativas divinas de Cristo', 3, 3, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (37, 37, '¿El Espíritu Santo tiene: Mente, voluntad y emociones?', 1, 1, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (38, 38, '¿Cuántos son los dones del Espíritu Santo?, mencionar', 3, 1, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (39, 39, '¿Con cuales otros nombres se conoce el Espíritu Santo?', 3, 3, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (40, 40, 'Según 1 Juan 5:8 ¿quienes son los que dan testimonio aquí en la tierra, el espíritu, el agua y la sangre?', 1, 3, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (41, 41, '¿Cuántos días permaneció Jesús en la tierra luego de haber resucitado?', 3, 1, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (42, 42, '¿Sobre qué les hablo Cristo a los discípulos, luego de haber resucitado?', 3, 2, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (43, 43, '¿De que tribu procedía Cristo?', 2, 1, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (44, 44, '¿En que río fue bautizado nuestro Señor Jesucristo?', 3, 1, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (45, 45, '¿El Espíritu Santo estaba activo en la transmisión del mensaje de Dios a su pueblo?', 1, 1, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (46, 46, '¿El Espíritu de Dios impartía liderazgo en el Antiguo Testamento?', 1, 1, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (47, 47, '¿Por quien fue llevado Jesús al desierto?', 2, 2, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (48, 48, '¿De que convence el Espíritu Santo?', 3, 2, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (49, 49, '¿En que ciudad iban a recibir los discípulos la promesa del Espíritu Santo?', 2, 1, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (50, 50, '¿Dónde iban a testificar los discípulos después de haber recibido la promesa del Espíritu Santo?', 3, 2, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (51, 51, '¿Quiénes fueron escogidos para la construcción del tabernáculo para la obra artística, según (Éxodo 31:1-11)?', 2, 3, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (52, 52, '¿Sobre cuales jueces vino el Espíritu Santo?', 3, 3, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (53, 53, 'Mencione cuales son los dones del Espíritu Santo', 3, 3, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (54, 54, '¿Quién es el mediador entre Dios y los Hombres?', 2, 1, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (55, 55, '¿El Espíritu Santo intercede por nosotros?', 1, 2, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (56, 56, '¿Cómo se presentó Jesús en el libro de Juan, con los siete "Yo soy"?', 3, 4, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (57, 57, '¿El Espíritu Santo nos despoja del viejo hombre?', 1, 2, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (58, 58, 'Según 1 Juan 5:7 ¿quienes son los que dan testimonio en el cielo?', 3, 2, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (59, 59, 'El Espíritu Santo como agente santificador, ¿Qué cambios hace en el creyente?', 3, 4, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (60, 60, '¿Cómo se manifiesta el Espíritu Santo en el creyente como agente de servicio?', 3, 3, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (61, 61, '¿Cuan es la gran comisión?', 3, 1, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (62, 62, '¿Qué aplica la palabra regeneración en el creyente?', 3, 2, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (63, 63, '¿Tenía Jesús el ADN de María y José?', 1, 1, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (64, 64, '¿Qué representaba Moisés y Elías en el monte de la transfiguración?', 3, 2, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (65, 65, '¿Cuál de los discípulos le planteo a Jesús el hacer las enramada?', 2, 3, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (66, 66, '¿Cuántas enramadas le propuso hacer el discípulo a Jesús?', 2, 3, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (67, 67, '¿Qué significa la palabra Enramada?', 3, 4, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (68, 68, '¿La ascensión de Cristo nos enseña que nuestro maestro es:?', 3, 4, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (69, 69, '¿Cuál fue la obra de Cristo en la tierra?', 3, 3, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (70, 70, '¿Cuáles de estos símbolos no representa al Espíritu Santo?', 2, 1, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (71, 71, 'Mencione las cinco (5) esencias de Dios Padre', 3, 3, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (72, 72, '¿Cuántos recibieron la promesa en el aposento alto?', 2, 1, true, NULL, NULL);
INSERT INTO public.preguntas VALUES (73, 73, '¿Qué símbolos se hicieron presentes en el día de Pentecostés?', 2, 2, true, NULL, NULL);