INSERT INTO public.respuestas VALUES (1, 1, 'La Teología', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (2, 1, 'La Cristología', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (3, 1, 'La Neumatología', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (4, 1, 'Ninguna de las anteriores', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (5, 2, 'Tres divinidades en un solo Dios ', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (6, 3, 'La Cristología', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (7, 3, 'La Sociología', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (8, 3, 'La Angelología', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (9, 3, 'Ninguna de las anteriores', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (10, 4, '1 Jn 5:7; Mt 28:19; ', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (11, 5, 'La Santificación', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (12, 5, 'La Regeneración', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (13, 5, 'La Purificación', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (14, 5, 'Ninguna de las anteriores', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (15, 6, 'Espíritu ( Juan 4,24)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (17, 8, 'Isaías', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (18, 8, 'Ezequiel', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (19, 8, 'Malaquías ', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (20, 8, 'Ninguna de las anteriores', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (21, 9, 'El Elyon (Gn 14:18),El Shadai (Gn 17:1), El Roi (Gn 13-14), El Olam (Gn 21:33).', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (22, 10, 'A.C y D.C', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (23, 11, 'El Padre', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (24, 11, 'El Espíritu Santo', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (25, 11, 'Jesucristo', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (26, 11, 'Ninguna de las anteriores', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (27, 12, 'NO.', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (28, 13, 'SI.', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (29, 14, 'El apóstol Pablo', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (30, 14, 'Juan el Bautista ', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (31, 14, 'El Señor Jesús', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (32, 14, 'Todas las anteriores', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (33, 15, 'Santo y sin defecto. 1 P 1:19', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (34, 16, 'Hablar en lenguas', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (35, 16, 'Danzar', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (36, 16, 'Todas las anteriores', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (37, 16, 'Ninguna de las anteriores', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (38, 17, 'Completamente hombre y completamente Dios', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (39, 18, 'El único que posee dos naturalezas entre los hombres', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (40, 19, 'Partenogenético (Sin la acción del espermatozoide de José)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (41, 20, 'La Naturaleza divina ', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (42, 20, 'La Naturaleza humana', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (43, 20, 'La reencarnación ', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (44, 20, 'Todas las anteriores', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (45, 21, 'para presentar a Cristo como: legitimo israelita, legítimo rey y legitimo mesías', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (46, 22, 'Perdonar, sanar, resucitar y proveer ', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (47, 23, 'Monte Alto', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (48, 24, 'FALSO', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (49, 25, 'Elías y Moisés. Mr 9:4; Lc 9:30', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (50, 26, 'Pedro, Juan y Jacobo', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (51, 27, 'Bautismo en agua (Jn 1:26), Bautismo en el Espíritu (Hch 1:5) y Bautismo en el cuerpo de Cristo (1 Co 12:13).', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (52, 28, 'Hechos 13:2', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (53, 29, 'Son siete (7) símbolos: Viento (Hch 2:2; Jn 3:8), Aceite (Hch 10:38), Agua (Jn 4:14), Paloma (Jn 1:32-34), Arras (Ef 1:13-14), Fuego (Mal 3:2) y Sello (2 Co 1:22)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (54, 30, 'FALSO', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (55, 31, 'Joel 2:28', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (56, 32, 'Jehová Jireh (Gn 22:11), Jehová Rapha (Ex 15:26), Jehová Nissi (Ex 17:15), Jehová Shalom (Ju 6:24)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (57, 33, 'Que esta en todo lugar (Sal 139:7)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (58, 34, 'Los profetas lo llaman: Dios fuerte, Padre Eterno, Admirable (Is 9:6) e Hijo de Dios (Jn 1:34)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (59, 35, 'Cristo el hijo del Dios viviente (Mt 16:15), Señor y Dios (Jn 20:28), El gran Dios mi salvador (Tito 2:13)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (60, 36, 'Creador (Jn 1:3), Dador de la vida (Jn 1:4), Salvador (Hch 4:12), Perdonador de pecados (Lc 5:24)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (61, 37, 'Si. Mente (Rm 8:27), Voluntad (1 Co 12:11), Emociones (Ef 4:30)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (62, 38, 'Son nueve (9) dones (1 Co 12:8)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (63, 39, 'Espíritu de Dios (Gn 1:2), Espíritu de Cristo (Rm 8:9), El Consolador (Jn 14:16), Espíritu de la Promesa (Ez 36:27), Espíritu de verdad (Jn 16:13), Espíritu de gracia (He 10:29), Espíritu de vida (Rm 8:2; Ap 11:11) y Espíritu de adopción (Rm 8:15)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (64, 40, 'Si, Verdadero', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (65, 41, 'Cuarenta (40) días (Hch 1:3)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (66, 42, 'Acerca del Reino de Dios (Hch 1:3)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (67, 43, 'Judá', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (68, 43, 'Leví', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (69, 43, 'Benjamín', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (70, 43, 'Rubén', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (71, 44, 'En el río Jordán (Mt 3:13)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (72, 45, 'Si. Verdadero (Neh 9:20)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (73, 46, 'Si, Verdadero (Nm 27:18; Ju 6:34)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (74, 47, 'Por el Espíritu', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (75, 47, 'Por Satanás', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (76, 47, 'Todas las anteriores', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (77, 47, 'Ninguna de las anteriores', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (78, 48, 'De pecado, de justicia y de juicio (Jn 16:8)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (79, 49, 'Jerusalén', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (80, 49, 'Judea', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (81, 49, 'Samaria', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (82, 49, 'Galilea', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (83, 50, 'Jerusalén, Judea, Samaria y hasta lo último de la tierra (Hch 1:8)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (84, 51, 'Caleb y Josué', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (85, 51, 'Moisés y Josué', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (86, 51, 'Bezaleel y Aholiab', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (87, 51, 'Ninguna de las anteriores', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (88, 52, 'Otoniel (Jc 3:10), Gedeón (Jc 6:34), Jefté (Jc 11:29), Samsun (Jc 14:6)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (89, 53, 'Palabra de sabiduría, Palabra de ciencia, Fe, Sanidades, Hacer Milagros, Profecía, Discernimiento de espíritu, Diversos géneros de lenguas y Interpretación de lenguas (1 Co 12:8-10)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (90, 54, 'El Hijo', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (91, 54, 'El Padre', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (92, 54, 'El Espíritu Santo', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (93, 54, 'Todas las anteriores', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (94, 55, 'Si, Verdadero (Rm 8:26)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (95, 56, '"YO SOY" El Pan de vida (Jn 6:35), La luz del mundo (Jn 8:12), La puerta de las ovejas (Jn 10:7), El buen pastor (Jn 10:11,14), La resurrección y la vida (Jn 11:25), El camino, y la verdad, y la vida (Jn 14:6) , La vid verdadera (Jn 15:1) ', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (96, 57, 'Si, Verdadero (Ef 4:22-24)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (97, 58, 'El Padre, El Verbo y el Espíritu Santo', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (98, 59, 'Santifica (Rm 8:9), Libra de la esclavitud del pecado (Rm 8:2-4), da certeza de ser hijos de Dios (Rm 8:16), estimula al creyente a la adoración (Rm 8:26-27), produce el carácter de Cristo (Ga 5:22-23), dirige a una comunión intima (Jn 14:16-18)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (99, 60, 'Autoridad para dar testimonio (Hch 1:8), poder para proclamar la palabra y hacer milagros (Hch 4:31; 2:43)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (100, 61, 'Predicar el evangelio (Mt 28:19)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (101, 62, 'Aplica un nuevo nacimiento y resurrección (Tito 3:5; Jn 3:3)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (102, 63, 'NO. Falso', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (103, 64, 'Moisés representaba la ley y Elías representaba los profetas', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (104, 65, 'Juan el Bautista ', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (105, 65, 'Juan y Jacobo', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (106, 65, 'Pedro', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (107, 65, 'Ninguna de las anteriores', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (108, 66, 'Cuatro (4)', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (109, 66, 'Tres (3)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (110, 66, 'Una (1)', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (111, 66, 'Mas de Cuatro (4)', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (112, 67, 'Cabaña, Tienda, Tabernáculo', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (113, 68, 'El Cristo celestial (Hch 1:10), el Cristo exaltado (Mt 28:18), el Cristo soberano (1 Co 11:3)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (114, 69, 'Sus milagros (Hch 2:22; 10:38), su obra expiatoria (1 Co 15:3; 2 Co 5:21), su resurrección (Mt 28:6)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (115, 70, 'Agua y Fuego', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (116, 70, 'Martillo y Oro', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (117, 70, 'Paloma y Aceite', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (118, 70, 'Ninguna de las anteriores', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (119, 71, 'Dios es Espíritu (Jn4:23-24), Dios es vida (Jn 5:26), Dios es perfecto (Mt 5:48), Dios es único (Is 40:25), Dios es eterno (Sal 90:2)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (120, 72, 'Ciento veinte (120)', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (121, 72, 'Ciento cincuenta (150)', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (122, 72, 'Doce (12)', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (123, 72, 'Solo los Apóstoles', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (124, 73, 'Agua y Paloma', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (125, 73, 'Viento y Fuego', true, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (126, 73, 'Aceite y Sello', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (127, 73, 'Todas las anteriores', false, true, NULL, NULL);
INSERT INTO public.respuestas VALUES (16, 7, 'Omnipresente, Omnisciente, Omnipotente, Soberano, Inmutable', true, true, NULL, NULL);

